stages:
  - build
  - deploy

build_image:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.sebbo.net
    - docker build -t docker.sebbo.net/sebbo2002/plex-fhem-lightscenes .
    - docker push docker.sebbo.net/sebbo2002/plex-fhem-lightscenes
  only:
    - master

publish_github:
  stage: build
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/plex-fhem-lightscenes.git" --all
    - git push "https://${GITHUB_AUTH}@github.com/sebbo2002/plex-fhem-lightscenes.git" --tags

trigger_dockerhub:
  stage: deploy
  tags:
    - matt.sebbo.net
    - ssh
  script:
    - curl -X "POST" "https://registry.hub.docker.com/u/sebbo2002/plex-fhem-lightscenes/trigger/ce6e5469-8772-4e49-a08b-969876172a56/"
  only:
    - master
